name: Discussion TODOs to Issues

permissions:
  issues: write
  discussions: read

on:
  discussion:
    types: [created]

jobs:
  discussion_todos_to_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create issues from TODOs in meeting minutes (with sub issues)
        uses: actions/github-script@v7
        with:
          script: |
            const discussion = context.payload.discussion;
            if (discussion.category.name !== "회의록") {
              console.log("카테고리가 회의록이 아니므로 종료합니다.");
              return;
            }
            const lines = discussion.body.split('\n');
            let inTodoSection = false;
            let currentAssignee = null;
            let parentIssue = null;
            for (let i = 0; i < lines.length; i++) {
              const line = lines[i];

              // "TODO" 섹션 시작
              if (/^#+\s*TODO/i.test(line.trim())) {
                inTodoSection = true;
                currentAssignee = null;
                parentIssue = null;
                continue;
              }

              // 섹션이 끝나는 조건(다음 헤더 등)
              if (inTodoSection && /^#+\s*\S+/.test(line.trim()) && !/^#+\s*TODO/i.test(line.trim())) {
                inTodoSection = false;
                currentAssignee = null;
                parentIssue = null;
                continue;
              }

              if (!inTodoSection) continue;

              // @username 줄 찾기
              const assigneeMatch = line.trim().match(/^@(\w+)/);
              if (assigneeMatch) {
                currentAssignee = assigneeMatch[1];
                parentIssue = null;
                continue;
              }

              // 체크박스 찾기 (들여쓰기 포함)
              const todoMatch = line.match(/^(\s*)- \[ \] (.+)/);
              if (todoMatch && currentAssignee) {
                const indent = todoMatch[1].length;
                const todoText = todoMatch[2].trim();

                if (indent === 0) {
                  // 부모 이슈 생성
                  const issue = await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: todoText,
                    body: `이 이슈는 회의록 Discussion에서 자동 생성되었습니다.\n\n[원본 Discussion 링크](${discussion.html_url})`,
                    assignees: [currentAssignee],
                    labels: ["회의록-TODO"]
                  });
                  parentIssue = issue.data.number;
                } else if (indent >= 2 && parentIssue) {
                  // sub issue 생성, 부모 이슈 번호를 본문에 남김
                  await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: todoText,
                    body: `부모 이슈: #${parentIssue}\n\n이 이슈는 회의록 Discussion에서 자동 생성되었습니다.\n\n[원본 Discussion 링크](${discussion.html_url})`,
                    assignees: [currentAssignee],
                    labels: ["회의록-TODO", "sub-issue"]
                  });
                }
              }
            }
